import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import './styles/reset.css'
import './globals.css'
import { TopBar } from './components/TopBar'
import { CategoryProvider } from './context/CategoryContext'

const comfortaa = Comfortaa({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'HP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={comfortaa.className}>
        <CategoryProvider>
          <TopBar />
          {children}
        </CategoryProvider>
      </body>
    </html>
  )
}
